(ns driving-cycle.core
  (:gen-class))

(defn proxy-with-prev-result
  "Returns an arg-less function that calls the given function with the
  result of its previous invocation (or the given initial value, if
  it's the first invocation)."
  [func initial]
                                        ; prev is result of the previous invocation
                                        ; using ref for thread safety
  (let [prev (ref initial)]
    (fn []
      (dosync (alter prev func))))
  )

(defn generate
  "Returns a lazy sequence of data generated by repeated invocations
  of the given function.

  The given function must accept the result of its previous invocation
  as an argument.

  On its first invocation the given initial value is passed in
  instead."
  [func-next-step initial]
  (repeatedly (proxy-with-prev-result func-next-step initial)))
