(ns driving-cycle.inputdata
  (:require [driving-cycle.common :as common])
  (:gen-class))

(defn generate
  "Returns a lazy sequence of data generated by repeated invocations
  of the given function.

  The given function must accept the result of its previous invocation
  as an argument.

  On its first invocation the given initial value is passed in
  instead."
  [func-next-step initial]
  (repeatedly (common/proxy-with-prev-result func-next-step initial)))
